// <auto-generated />
using System;
using GAtreeWebStore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GAtreeWebStore.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20220104220203_AddURL2Data")]
    partial class AddURL2Data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GAtreeWebStore.Models.Data", b =>
                {
                    b.Property<int>("Data_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Data_URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data_friendlyname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Data_guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Data_header")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Data_json")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Data_notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Data_id");

                    b.ToTable("GATreeData");
                });

            modelBuilder.Entity("GAtreeWebStore.Models.DataAttributes", b =>
                {
                    b.Property<int>("DataAttributes_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DataAttributes_attributesData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DataAttributes_isClass")
                        .HasColumnType("bit");

                    b.Property<string>("DataAttributes_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DataAttributes_sn")
                        .HasColumnType("int");

                    b.Property<string>("DataAttributes_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Data_guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("data_DataAttributes_data_ID")
                        .HasColumnType("int");

                    b.HasKey("DataAttributes_Id");

                    b.HasIndex("data_DataAttributes_data_ID");

                    b.ToTable("GATreeDataAttributes");
                });

            modelBuilder.Entity("GAtreeWebStore.Models.DataAttributes", b =>
                {
                    b.HasOne("GAtreeWebStore.Models.Data", "Data")
                        .WithMany()
                        .HasForeignKey("data_DataAttributes_data_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Data");
                });
#pragma warning restore 612, 618
        }
    }
}
